name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: prepare workspace
        run: cp -r src unity/Assets/Editor/VibingTools

      - name: pack unitypackage
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: 'unityci/editor:2022.3.22f1-base-3'
          projectPath: unity
          targetPlatform: StandaloneWindows64
          buildMethod: ExportUnityPackage.Export

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VibingTools.unitypackage
          path: unity/Build/VibingTools.unitypackage